### ISSUE TITLE
cleaning the build_XX folder

### ISSUE THREAD

**Issue by Foadsf** [SimulIDE/SimulIDE#17]
putting the `SimulIDE_Build.pro` file in the `build_XX` folder seems like a bad practice to me. we should

- move the `SimulIDE_Build.pro` to the root folder
- remove the `build_XX` and put it and the `build` directories in the `.gitignore` file 

Idelally we should have a compiling instructions of

   - `mkdir build`
   - `cd build`
   - `qmake ..`
   - `make`

and make sure the `build`  folders never end up in the git history.

**Comment by Mihaylov93** [comment]
As discussed on Discord, in my opinion that .pro and folder are unnecessary. Qt has a thing called [shadow builds](https://wiki.qt.io/Qt_shadow_builds), and QtCreator uses them by default. 
An example:
```
$ ls
build_XX/                                                       LICENSE
build-SimulIDE_Build-Desktop_Qt_MinGW_w64_32bit_MSYS2-Debug/    README.md
build-SimulIDE_Build-Desktop_Qt_MinGW_w64_32bit_MSYS2-Release/  resources/
changelog.txt                                                   SimulIDE.pro
COPYING                                                         src/
```

And judging by the folder and .pro it seems like an ugly hack to recreate a feature that already exist.

```
BUILD_DIR = $$PWD

include(../SimulIDE.pro)
```

For the gitignore `*build-*` is enough to avoid having the folders in the commits.

We should follow qt guidelines, they have it nicely explained here https://doc.qt.io/qt-5/configure-options.html#source-build-and-install-directories
