### ISSUE TITLE
Translations *.qm should be removed from tracked files.

### ISSUE THREAD

**Issue by Mihaylov93** [SimulIDE/SimulIDE#30]
Files with .qm extension are release related files and should not be part of the source. 
SimulIDE/master/resources/translations/*.qm

As they are being tracked from before the update of the .gitignore https://github.com/SimulIDE/SimulIDE/blob/43e3bdf48e6935bdc3e7dced3bb5ce4af755da2c/.gitignore#L246 has no effect until we remove them from tracked files.

**Comment by saptarsi96** [comment]
Hi, @Mihaylov93 I would like to work on this.

**Comment by Mihaylov93** [comment]
Solved by   4c458e0
