### ISSUE TITLE
Typo in method name

### ISSUE THREAD

**Issue by Mihaylov93** [SimulIDE/SimulIDE#37]
https://github.com/SimulIDE/SimulIDE/blob/3141bc9c344f29be680e2ecad025da2e4bd7a625/src/mainwindow.cpp#L347

**Comment by stefandiaconu** [comment]
Please assign this to me.

**Comment by Mihaylov93** [comment]
Done, but you can work on any issue without being assigned :)

Thats the power of open source. Just send your Pull Request and there is no problem.

**Comment by Mihaylov93** [comment]
Closed by PR #39
